# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/linux-qt6-next.yml
      - /gitlab-templates/alpine-qt6.yml
      - /gitlab-templates/xml-lint.yml
      - /gitlab-templates/yaml-lint.yml

posix-script-compliance:
  image:
    name: debian:latest
    entrypoint: [""]
  tags:
    - Linux
  stage: build
  script:
    - apt-get update
    - apt-get -y install shellcheck
    - shellcheck -x -s sh bin/startplasmamobile.in
    - shellcheck -x -s sh bin/startplasmamobile.in
    - shellcheck -x --exclude=1091 -s sh bin/startplasmamobile-dev.sh.cmake # ignore error from file not existing (given by cmake)


# Ensure i18n is not used with single quotes
check-i18n-single-quote:
  image:
    name: debian:latest
    entrypoint: [""]
  tags:
    - Linux
  stage: validate
  script:
    - echo "Checking for i18n* usage in QML files to make sure single quotes aren't used..."
    - if grep -RIn --include="*.qml" -E "i18n(c(p)?|d(c?p)?|n(p)?)?\('" .; then
        echo "Found single quote i18n* usage in QML. Please correct these to use double quotes instead.";
        exit 1;
      else
        echo "No single quote i18n* usage found in QML.";
      fi
